import { models } from '../config/constants'

let mongoose = require('mongoose')
let ObjectId = mongoose.Schema.ObjectId

var schema = new mongoose.Schema({
	name: {type: String, required: true},
	created: {type: Number, default: Date.now()},	
	isSold: {type: Boolean},
    conditionalOffer: {type: Boolean},
    activeListing: {type: Boolean},
    isFeature: {type: Boolean, default: false},
    relatedImages: {type: Array},   
    listingPrice: {type: Number},
    redirectionUrl: {type: String},
    lotSize: {type: String},
    legal: {type: String},
    directions: {type: String},
    taxes: {type: Number},
    year: {type: Number},
    survey:  {type: String},
    propertyDisclosure:  {type: String},
    use:  {type: String},
    title: {type: String},
    water: {type: Boolean},
    sewer: {type: Boolean},
    basement: {type: Boolean},
    propSize: {type: String},
    siteInfluences: {type: String},
    waterfront: {type: Boolean},
    bodyOfWater: {type: Boolean},
    numStories: {type: Number},
    frontage: {type: String},
    buildingDiv: {type: String},
    totalArea: {type: String},
    officeArea: {type: String},
    whseArea: {type: String},
    ceiling: {type: String},
    construction: {type: String},
    power:  {type: Boolean},
    amps: {type: Number},
    heatAir: {type: Boolean},
    whseHeatAir: {type: Boolean},
    fuel:  {type: String},
    loading:  {type: String},
    numRentalUnits: {type: Number},
    area:  {type: String},
    features:  {type: String},
    mortage: {type: Number},
    exclusions:  {type: String},
    remarks:  {type: String},
    agreement: {type: String},
    occupants: {type: Number},
    howShown:  {type: String},
    salePrice: {type: Number},
    saleDate: {type: Number}
	
});

module.exports = mongoose.model(models.property.name, schema);